# Generated by Django 4.0.4 on 2022-09-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_address_alter_user_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_provider',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
